"""Builds rebuild_database.sql: one script that resets a Supabase database and
rebuilds the website's schema from supabase/migrations.

    python3 supabase/rebuild/build_rebuild_sql.py [project-ref]

Order of the generated script:
  1. reset.sql   - drops what a new Lovable project created in `public` and `private`
                   (logins and uploaded files are kept)
  2. the setup files from the 22 May 2026 catch-up onward, each in its own
     transaction (files that add enum values must commit before the values are used)
  3. bridge.sql  - inserted before the September files; adds columns the live
                   database had from earlier setup files that the catch-up does not create

Files before the catch-up belonged to earlier projects and conflict with it, so
they are left out. Lovable's own files from 28 Sep 2026 describe the schema being
replaced and are left out too.
"""
import glob
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MIGRATIONS = os.path.join(HERE, "..", "migrations")
START = "20260522092420"          # 22 May 2026 catch-up
BRIDGE_BEFORE = "20260923"        # first file that needs the bridge columns
SKIP_PREFIXES = ("20260928",)     # the new Lovable project's own schema
OLD_PROJECT = "oymqqsvabbzognjgbxtl"
project = sys.argv[1] if len(sys.argv) > 1 else "cncojvwliuxismhsuewf"

files = sorted(
    f for f in glob.glob(os.path.join(MIGRATIONS, "*.sql"))
    if os.path.basename(f) >= START and not os.path.basename(f).startswith(SKIP_PREFIXES)
)
read = lambda name: open(os.path.join(HERE, name)).read().rstrip()

out = [f"""-- =====================================================================
-- Concepts Learning Academy: rebuild the database to match the website
-- =====================================================================
-- Run this ONCE on the new project's database, pasting the whole file
-- into the SQL editor and running it in one go.
--
-- STEP 1 deletes the tables, functions and storage policies the new
--        Lovable project created, and ALL data in them. Logins and
--        uploaded files are kept.
-- STEP 2 builds the website's database from its {len(files)} setup files in
--        supabase/migrations, starting at the 22 May 2026 catch-up. Earlier
--        files belonged to previous projects and are superseded by it.
--        Each file is committed on its own.
-- BRIDGE adds 13 columns the live database had from older setup files.
--
-- The school-agent schedule is pointed at project {project}.
--
-- Tested on PostgreSQL 16 against a copy of the new project's tables: the
-- result has every table, column and database function the website uses.
--
-- Generated by supabase/rebuild/build_rebuild_sql.py. Do not edit by hand.
-- =====================================================================
SET search_path = public, extensions;
""", "\n" + read("reset.sql") + "\n"]

bridge_done = False
for f in files:
    name = os.path.basename(f)
    if not bridge_done and name >= BRIDGE_BEFORE:
        out.append(f"\n-- ---- BRIDGE ----\nBEGIN;\n{read('bridge.sql')}\n;\nCOMMIT;\n")
        bridge_done = True
    body = open(f).read().rstrip().replace(OLD_PROJECT, project)
    out.append(f"\n-- ---- {name} ----\nBEGIN;\n{body}\n;\nCOMMIT;\n")
out.append("\nSELECT 'Concepts Learning Academy database rebuilt' AS result;\n")

target = os.path.join(HERE, "rebuild_database.sql")
open(target, "w").write("".join(out))
print(f"wrote {os.path.relpath(target)}: {len(files)} setup files")
