ALTER TABLE public.bank_transactions ADD COLUMN IF NOT EXISTS amount_zig NUMERIC(14,2), ADD COLUMN IF NOT EXISTS account_number TEXT, ADD COLUMN IF NOT EXISTS notes TEXT, ADD COLUMN IF NOT EXISTS recorded_by UUID;

ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS is_examinable BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE public.subjects ALTER COLUMN code DROP NOT NULL;
ALTER TABLE public.subjects ALTER COLUMN code SET DEFAULT '';

ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS level TEXT, ADD COLUMN IF NOT EXISTS academic_year TEXT;
ALTER TABLE public.classes ALTER COLUMN level_name DROP NOT NULL;
ALTER TABLE public.classes ALTER COLUMN level_name SET DEFAULT '';

ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS full_name TEXT, ADD COLUMN IF NOT EXISTS email TEXT, ADD COLUMN IF NOT EXISTS role TEXT, ADD COLUMN IF NOT EXISTS category TEXT, ADD COLUMN IF NOT EXISTS status TEXT, ADD COLUMN IF NOT EXISTS department TEXT, ADD COLUMN IF NOT EXISTS subjects_taught TEXT[];
ALTER TABLE public.staff ALTER COLUMN staff_number DROP NOT NULL;
ALTER TABLE public.staff ALTER COLUMN first_name DROP NOT NULL;
ALTER TABLE public.staff ALTER COLUMN last_name DROP NOT NULL;
ALTER TABLE public.staff ALTER COLUMN position DROP NOT NULL;
ALTER TABLE public.staff ALTER COLUMN employment_status DROP NOT NULL;